spring:
  application.name: my-blog
  datasource:
    url: "jdbc:h2:mem:my_blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:

hibernate.dialect: org.hibernate.dialect.H2Dialect

server:
  port: 8020

